from __future__ import annotations

import json
import os
from typing import Any

from openai import APITimeoutError, OpenAI

from services.logger import logger
from services.metrics import metrics_store


PRIMARY_MODEL = "meta/llama-3.1-70b-instruct"
FALLBACK_MODEL = "mistralai/mistral-7b-instruct"


def _client() -> OpenAI:
    return OpenAI(
        api_key=os.getenv("NVIDIA_API_KEY"),
        base_url=os.getenv("NVIDIA_BASE_URL", "https://integrate.api.nvidia.com/v1"),
        timeout=10.0,
    )


def _build_prompt(prompt_type: str, context_data: dict[str, Any]) -> str:
    if prompt_type == "risk_explanation":
        return (
            "You are TrustLayer AI, a financial security assistant.\n"
            f"A transaction was analyzed with the following risk factors: {json.dumps(context_data.get('risk_factors', []))}.\n"
            f"The risk score is {context_data.get('risk_score')}/100 and the decision is {context_data.get('decision')}.\n"
            "Write a clear, friendly 2-sentence explanation for why this decision was made.\n"
            "Be specific about which factors triggered the alert.\n"
            "Do not use technical jargon. Write as if explaining to the bank customer."
        )
    if prompt_type == "credit_tips":
        return (
            "You are TrustLayer AI, a helpful credit coach.\n"
            f"Use this breakdown: {json.dumps(context_data.get('breakdown', {}))}.\n"
            "Return 2 short, actionable improvement tips for the customer."
        )
    if prompt_type == "assistant_chat":
        return context_data["prompt"]
    return json.dumps(context_data)


def _template_fallback(prompt_type: str, context_data: dict[str, Any]) -> str:
    risk_factors = context_data.get("risk_factors", [])
    decision = context_data.get("decision")
    top_factor = risk_factors[0]["type"] if risk_factors else None

    if prompt_type != "risk_explanation":
        return "This result was generated by TrustLayer's fallback explanation path."

    if decision == "block" and top_factor == "amount_deviation":
        return "This transaction was blocked because the amount is significantly higher than your normal spending pattern."
    if decision == "verify" and top_factor == "new_device":
        return "We need to verify this transaction because it was initiated from a device you have not used before."
    if decision == "verify" and top_factor == "location_anomaly":
        return "This transaction needs verification because it is coming from an unusual location."
    if decision == "block" and top_factor == "high_velocity":
        return "Multiple transactions were detected in a short period. This transaction has been paused for your protection."
    return "This transaction was flagged by our security system. Please contact your bank if you believe this is an error."


def _run_model(model: str, prompt: str) -> str:
    completion = _client().chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
    )
    return (completion.choices[0].message.content or "").strip()


def explain(prompt_type: str, context_data: dict[str, Any]) -> dict[str, Any]:
    prompt = _build_prompt(prompt_type, context_data)
    model_used = PRIMARY_MODEL
    fallback_level = 0

    try:
        explanation = _run_model(PRIMARY_MODEL, prompt)
    except Exception as primary_error:
        fallback_level = 1
        metrics_store.record_llm_fallback()
        logger.warning("llm_primary_failed", reason=str(primary_error), fallback_level=fallback_level, model_used=PRIMARY_MODEL)
        try:
            model_used = FALLBACK_MODEL
            explanation = _run_model(FALLBACK_MODEL, prompt)
        except Exception as secondary_error:
            fallback_level = 2
            metrics_store.record_llm_fallback()
            model_used = "template_fallback"
            logger.warning("llm_secondary_failed", reason=str(secondary_error), fallback_level=fallback_level, model_used=FALLBACK_MODEL)
            explanation = _template_fallback(prompt_type, context_data)

    return {
        "explanation": explanation,
        "model_used": model_used,
        "fallback_level": fallback_level,
    }
